# Generated by Django 4.2 on 2023-04-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Srticle',
            new_name='Article',
        ),
    ]
